---
abstract: 'Parse GEDCOM dates'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Genealogy-Gedcom-Date
provides:
  Genealogy::Gedcom::Date:
    file: lib/Genealogy/Gedcom/Date.pm
    version: 1.05
requires:
  DateTime: 0.72
  DateTime::Infinite: 0.72
  Hash::FieldHash: 0.12
  Try::Tiny: 0.11
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.05
