#!/bin/bash

perl -Ilib scripts/parse.pl -max info -d '15 Jul 1954'
perl -Ilib scripts/parse.pl -max info -d '10 JUL 2003'
perl -Ilib scripts/parse.pl -max info -d 'JUL 2003'
perl -Ilib scripts/parse.pl -max info -d '2003'
perl -Ilib scripts/parse.pl -max info -d 'ABT 10 JUL 2003'
perl -Ilib scripts/parse.pl -max info -d 'CAL 1922'
perl -Ilib scripts/parse.pl -max info -d 'CAL 10 JUL 2003'
perl -Ilib scripts/parse.pl -max info -d 'EST 1700'
perl -Ilib scripts/parse.pl -max info -d 'EST 10 JUL 2003'
perl -Ilib scripts/parse.pl -max info -d 'FROM 1522 TO 1534'
perl -Ilib scripts/parse.pl -max info -d 'FROM 30 APR 1980'
perl -Ilib scripts/parse.pl -max info -d 'FROM 10 JUL 2003'
perl -Ilib scripts/parse.pl -max info -d 'TO 1910'
perl -Ilib scripts/parse.pl -max info -d 'TO 10 JUL 2003'
perl -Ilib scripts/parse.pl -max info -d 'FROM 10 JUL 2003 TO 20 JUL 2003'
perl -Ilib scripts/parse.pl -max info -d 'AFTER 1948'
perl -Ilib scripts/parse.pl -max info -d 'AFT 10 JUL 2003'
perl -Ilib scripts/parse.pl -max info -d 'BEF 2 AUG 2003'
perl -Ilib scripts/parse.pl -max info -d 'BEF 10 JUL 2003'
perl -Ilib scripts/parse.pl -max info -d 'BET 1600 AND 1620'
perl -Ilib scripts/parse.pl -max info -d 'BET 1 JAN 1852 AND 31 DEC 1852'
perl -Ilib scripts/parse.pl -max info -d 'BET 1 JAN 1852 AND DEC 1852'
perl -Ilib scripts/parse.pl -max info -d 'BET JAN 1852 AND 31 DEC 1852'
perl -Ilib scripts/parse.pl -max info -d 'BET JAN 1852 AND DEC 1852'
perl -Ilib scripts/parse.pl -max info -d 'BET 1 JAN 1920 AND 31 JAN 1920'
perl -Ilib scripts/parse.pl -max info -d 'BET 10 JUL 2003 AND 20 JUL 2003'
perl -Ilib scripts/parse.pl -max info -d 'Aft 1 Jan 2001'
perl -Ilib scripts/parse.pl -max info -d 'From 0'
perl -Ilib scripts/parse.pl -max info -d 'Abt 1 Jan 2001'
perl -Ilib scripts/parse.pl -max info -d 'Abt 4000 BC'
perl -Ilib scripts/parse.pl -max info -d 'Cal 2345 BC'
perl -Ilib scripts/parse.pl -max info -d 'Cal 31 Dec 2000'
perl -Ilib scripts/parse.pl -max info -d 'Est 1 Jan 2001'
perl -Ilib scripts/parse.pl -max info -d 'Est 1234BC'
perl -Ilib scripts/parse.pl -max info -d 'FROM 1904 to 1915'
perl -Ilib scripts/parse.pl -max info -d 'FROM 1904'
perl -Ilib scripts/parse.pl -max info -d 'TO 1915'
perl -Ilib scripts/parse.pl -max info -d 'From 2011 BC to 4 Mar 2011'
perl -Ilib scripts/parse.pl -max info -d 'From 2 Jan 2011 to 4 Mar 2011'
perl -Ilib scripts/parse.pl -max info -d '16 Jan' 2011'
perl -Ilib scripts/parse.pl -max info -d '1 Dec 1699/00'
perl -Ilib scripts/parse.pl -max info -d 'INT 12 APR 1657 \(Easter Monday\)'
perl -Ilib scripts/parse.pl -max info -d 'INT 10 JUL 2003 \(foo\)'
perl -Ilib scripts/parse.pl -max info -d '\(Once upon a time\)'
perl -Ilib scripts/parse.pl -max info -d '\(foo\)'
perl -Ilib scripts/parse.pl -max info -d '1 Jan 1000'
perl -Ilib scripts/parse.pl -max info -d '1 Jan 900'
perl -Ilib scripts/parse.pl -max info -d '1950 B C'
perl -Ilib scripts/parse.pl -max info -d '1950 BC'
perl -Ilib scripts/parse.pl -max info -d '1950 B.C'
perl -Ilib scripts/parse.pl -max info -d '1950 BC.'
perl -Ilib scripts/parse.pl -max info -d '1950 B.C.'
perl -Ilib scripts/parse.pl -max info -d '1950 BCE'
perl -Ilib scripts/parse.pl -max info -d '21.mär.1999'
